server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Next 静态资源长缓存
  location /_next/static/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # 静态导出 / SPA 路由回退
  location / {
    try_files $uri $uri.html $uri/ /index.html;
  }
}
